name: Deploy Node.js App

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest

  deploy:
    runs-on: self-hosted  # Key change
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker pull nodejs-app:latest
          docker-compose up -d --build
