name: Deploy Node.js App

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest
          docker stop nodejs-app || true
          docker rm nodejs-app || true
          echo "${{ secrets.APP_ENV }}" > .env
          docker run -d --name nodejs-app -p 3000:3000 --env-file .env ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest
